### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Yucked** [purpledank/ClientOfClans#1]
https://github.com/purpledank/ClientOfClans/blob/5a07946eff430f2ff6a6ae0c397774eeddc5c97d/ClientOfClans/Requests.cs#L36

Set it when you create new HttpClient?
```cs
new HttpClient {
BaseAddress = new Uri("")
}
```

A log event instead of Console.WriteLine()?
https://github.com/purpledank/ClientOfClans/blob/5a07946eff430f2ff6a6ae0c397774eeddc5c97d/ClientOfClans/Requests.cs#L47

```cs
public event Action<string> Log;```

**Comment by k-boyle** [comment]
ooo didn't realise you could do the BaseAddress thank you, and the Console.WriteLine is just for my testing, not close to being done yet.
